#Build React app
FROM node:16 AS builder

WORKDIR /app
COPY . .
RUN yarn install && yarn build:railway:hom

#Host the app from the build folder (/app)
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*

COPY --from=builder /app/build .
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
#ENTRYPOINT ["nginx", "-g", "daemon off;"]